[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "parentApp Documentation"
authors = [{name = "Benjamin Schichtholz", email = "neben@mailbox.org"}]
dynamic = ["version", "description"]
